### ISSUE TITLE
Tests with unistore

### ISSUE THREAD

**Issue by 7Ds7** [preactjs-templates/default#15]
Regarding the test setup i am having troubles when it comes to wrap the element around a unistore Provider

This test will pass and it finds the h1 tag inside the Testable component
```
test('Render testc read h1', () => {
        const context = deep(<Testable />);
        console.log(context.output());
        expect(context.find('h1').length).toBe(1);
      });
```

This test will fail because it won't find the h1 inside the Testable component, although preact-render-to-string render function will print the markup properly
```
test('Render testc read h1', () => {
        const context = deep(<Provider store={store}><Testable /></Provider>);
        console.log(context.output());
        expect(context.find('h1').length).toBe(1);
    });
```

Somehow i have been struggling with this for weeks now and still did not manage to make it work.
Is it possible that one can not test components this way?

**Comment by developit** [comment]
Hi @7Ds7 - sorry for the delay, this repo isn't as actively monitored as the other Preact repos (or Unistore).

If you're seeing the right values from `preact-render-to-string`, it's possible `deep()` from `preact-render-spy` is the culprit here.

In general, I think most people avoid testing the already-connected components since it means you have to pass them a whole store, which is not great for test isolation.  Instead, typically you'll see people import the underlying prop-driven component without the connected wrapper in order to test it in isolation:

```js
import { Component } from 'preact';
import { connect } from 'unistore/preact';

const actions = { increment(state) { state.count++ } }

// you'd import this named export rather than the default export when testing
export const Counter = ({ count, increment }) => (
  <div>
    {count}
    <button onClick={increment}>Increment</button>
  </div>
)

export default connect('count', actions)(Counter);
```
